In [46]:
import numpy as np
import random

In [74]:
a = np.array([1,2,3])
b = np.array([[1.5,3.4,2.4],[3.7, 8.2,5.]], dtype= float)

In [51]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr = np.arange(0,11,2)
arr

In [ ]:
arr = np.zeros((2,3))
arr

In [ ]:
arr = np.ones((3,4))
arr

In [ ]:
arr= np.linspace(1,2,5)
arr

# Inspecting Numpy Arrays

In [ ]:
a.shape

In [ ]:
len (b)

In [ ]:
a.ndim

In [ ]:
b.size

In [ ]:
b.dtype

In [ ]:
b.astype(int)

In [ ]:
np.insert(a,1,9)

In [ ]:
np.delete(a,2)

In [61]:
b.reshape(3,2)

array([[1.5, 3.4],
       [2.4, 3.7],
       [8.2, 5. ]])

In [62]:
d= np.append(a,b)
d

array([1. , 2. , 3. , 5. , 1.5, 3.4, 2.4, 3.7, 8.2, 5. ])

# Subsetting, Slicing, & Indexing

In [63]:
a

array([1, 2, 3, 5])

In [64]:
a[2]

3

In [65]:
b

array([[1.5, 3.4, 2.4],
       [3.7, 8.2, 5. ]])

In [67]:
b[1][2]

5.0

# Numpy Array Mathematics

In [70]:
a


array([1, 2, 3, 5])

In [71]:
b

array([[1.5, 3.4, 2.4],
       [3.7, 8.2, 5. ]])

In [75]:
b+a

array([[ 2.5,  5.4,  5.4],
       [ 4.7, 10.2,  8. ]])

In [77]:
c=np.add(b,a)
c

array([[ 2.5,  5.4,  5.4],
       [ 4.7, 10.2,  8. ]])

In [79]:
d=np.subtract(b,a)
d

array([[ 0.5,  1.4, -0.6],
       [ 2.7,  6.2,  2. ]])

In [80]:
np.multiply(a,b)

array([[ 1.5,  6.8,  7.2],
       [ 3.7, 16.4, 15. ]])

In [81]:
np.sqrt(b)

array([[1.22474487, 1.84390889, 1.54919334],
       [1.92353841, 2.86356421, 2.23606798]])

In [82]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [84]:
np.log(c)

array([[0.91629073, 1.68639895, 1.68639895],
       [1.54756251, 2.32238772, 2.07944154]])

# NumPy Statistical Operations

In [85]:
a.sum()

6

In [87]:
b.min()

1.5

In [89]:
a.max()

3

In [90]:
a.mean()

2.0

In [92]:
np.median(a)

2.0

In [93]:
np.std(a)

0.816496580927726